spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://postgredb:5433/di_lab_2
    username: auto_test
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl_auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders_service
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
