server:
  port: 8082
spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:postgresql://192.168.1.240:5433/di_lab_2
    username: auto_test
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl_auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: warehouse_service
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: 192.168.1.240
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
    deserialization:
      trusted-packages: "*"
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    drop-first: true
    default-schema: warehouse_service
